from __future__ import annotations

RANGE_ROLE_UNKNOWN = 0
RANGE_ROLE_ORDINARY = 1
RANGE_ROLE_FLAT = 2
RANGE_ROLE_REFERENCE = 3

RANGE_FLAG_REVERSED = 1
RANGE_FLAG_DEGENERATE = 2
RANGE_FLAG_SUFFIXED = 4
RANGE_FLAG_OVER_WIDTH = 8
RANGE_FLAG_REFERENCE = 16

RANGE_FLAGS_EXCLUDED_FROM_ENDPOINT = (
    RANGE_FLAG_REVERSED
    | RANGE_FLAG_DEGENERATE
    | RANGE_FLAG_OVER_WIDTH
    | RANGE_FLAG_REFERENCE
)
RANGE_FLAGS_EXCLUDED_FROM_INTERIOR = (
    RANGE_FLAGS_EXCLUDED_FROM_ENDPOINT | RANGE_FLAG_SUFFIXED
)
RANGE_FLAGS_EXCLUDED_FROM_INDEX = RANGE_FLAGS_EXCLUDED_FROM_INTERIOR
